# ==============================================================================
# BINARIO LINUX - LIMITS CONFIGURATION (ESYNC / FSYNC / AUDIO / GAMING)
# ==============================================================================

# Soporte para Wine / Proton Esync & Fsync (evita límites de descriptores de archivos)
*               soft    nofile          524288
*               hard    nofile          1048576
root            soft    nofile          524288
root            hard    nofile          1048576

# Audio en tiempo real (PipeWire & Jack)
@audio          soft    rtprio          95
@audio          hard    rtprio          95
@audio          soft    memlock         unlimited
@audio          hard    memlock         unlimited

# Prioridad para GameMode y procesos de videojuegos
@gamemode       soft    nice            -20
@gamemode       hard    nice            -20
