#
# /etc/pacman.conf - Binario Linux Pacman Configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto

# Misc options
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
ILoveCandy

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# ------------------------------------------------------------------------------
# REPOSITORIOS OFICIALES DE ARCH LINUX
# ------------------------------------------------------------------------------

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Multilib es esencial para Steam, Wine y bibliotecas de 32-bit de Gaming
[multilib]
Include = /etc/pacman.d/mirrorlist
